import { useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, List, Check } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { useAppDispatch, useAppSelector, useUser } from '../../app/hooks';
import { selectOwnPlans } from '../../app/selectors';
import { actions } from '../../app/slices';
import { calendarDays, capitalize, dayLabel, monthEnd, monthLabel, offsetMonth, todayInRiyadh, validDate } from '../../domain/logic';
import type { OccurrenceStatus } from '../../domain/types';
import { ActionLink, Badge, Button, Card, Empty, ErrorSummary, Field, Modal, Notice, PageHeader } from '../../components/UI';
const statuses: OccurrenceStatus[] = ['scheduled', 'in_progress', 'blocked', 'completed', 'cancelled'];
export default function Calendar() {
    const dispatch = useAppDispatch(), month = useAppSelector(s => s.preferences.month), weekStart = useAppSelector(s => s.preferences.weekStart), plans = useAppSelector(selectOwnPlans), all = useAppSelector(s => s.planning.occurrences), [params, setParams] = useSearchParams(), [view, setView] = useState<'calendar' | 'agenda'>(() => window.innerWidth < 768 ? 'agenda' : 'calendar'), [status, setStatus] = useState('all'), [scope, setScope] = useState('all');
    const own = plans.filter(p => p.month === month), occurrences = Object.values(all).filter(o => own.some(p => p.id === o.planId) && (status === 'all' || o.status === status) && (scope === 'all' || own.find(p => p.id === o.planId)?.items.find(c => c.id === o.commitmentId)?.activity.scope === scope)).sort((a, b) => a.date.localeCompare(b.date));
    const details = (id: string) => own.find(p => p.items.some(c => c.id === id))?.items.find(c => c.id === id)?.activity;
    const edit = params.get('occurrence'), days = calendarDays(month, weekStart), today = todayInRiyadh();
    const open = (id: string) => setParams({ occurrence: id });
    return <><PageHeader eyebrow="DO A LITTLE, REGULARLY" title="Your practice calendar" description="A clear view of the moments you have planned. Update one occurrence at a time." action={<ActionLink to="/plan/new">Build another month</ActionLink>}/><div className="calendar-toolbar"><div className="row"><Button variant="secondary" aria-label="Previous month" onClick={() => dispatch(actions.preferences.set({ month: offsetMonth(month, -1) }))}><ChevronLeft size={16}/></Button><h2>{monthLabel(month)}</h2><Button variant="secondary" aria-label="Next month" onClick={() => dispatch(actions.preferences.set({ month: offsetMonth(month, 1) }))}><ChevronRight size={16}/></Button></div><div className="row"><Button variant={view === 'calendar' ? 'primary' : 'secondary'} onClick={() => setView('calendar')} aria-pressed={view === 'calendar'}><CalendarDays size={15}/>Month</Button><Button variant={view === 'agenda' ? 'primary' : 'secondary'} onClick={() => setView('agenda')} aria-pressed={view === 'agenda'}><List size={15}/>Agenda</Button></div></div><div className="filters"><label className="sr-only" htmlFor="calendar-status">Filter by status</label><select id="calendar-status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s => <option key={s} value={s}>{capitalize(s)}</option>)}</select><label className="sr-only" htmlFor="calendar-scope">Filter by scope</label><select id="calendar-scope" value={scope} onChange={e => setScope(e.target.value)}><option value="all">All scopes</option>{['individual', 'culture', 'team'].map(s => <option key={s} value={s}>{capitalize(s)}</option>)}</select><span className="small-text muted">{occurrences.length} visible occurrences · Asia/Riyadh</span></div>
 {!own.length ? <Card><Empty title="Nothing planned this month" description="Build a balanced monthly plan and your scheduled activities will appear here." action={<ActionLink to="/plan/new">Create a plan</ActionLink>}/></Card> : view === 'calendar' ? <><p className="calendar-mobile-note">The month grid scrolls horizontally. Use Agenda for a compact mobile view.</p><div className="calendar-container" tabIndex={0} role="region" aria-label="Monthly activity calendar"><div className="calendar-grid">{Array.from({ length: 7 }, (_, i) => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][(i + weekStart) % 7]).map(d => <div key={d} className="calendar-heading">{d}</div>)}{days.map(day => <div key={day.date} className={`calendar-day ${day.inMonth ? '' : 'outside'} ${day.date === today ? 'today' : ''}`}><span aria-label={dayLabel(day.date)}>{Number(day.date.slice(-2))}</span>{day.inMonth && occurrences.filter(o => o.date === day.date).map(o => <button key={o.id} className={`calendar-event ${o.status}`} aria-label={`${details(o.commitmentId)?.title}, ${dayLabel(o.date)}, ${capitalize(o.status)}`} onClick={() => open(o.id)}>{o.status === 'completed' ? '✓ ' : o.status === 'blocked' ? '! ' : ''}{details(o.commitmentId)?.title}</button>)}</div>)}</div></div><div className="calendar-legend">{statuses.map(s => <Badge key={s} tone={s}>{capitalize(s)}</Badge>)}</div></> : occurrences.length ? <div>{[...new Set(occurrences.map(o => o.date))].map(date => <section className="agenda-day" key={date}><h3>{dayLabel(date)}</h3>{occurrences.filter(o => o.date === date).map(o => <div key={o.id} className="agenda-item"><div className="date-tile"><strong>{Number(date.slice(-2))}</strong><span>{monthLabel(month).slice(0, 3)}</span></div><div className="grow"><h3>{details(o.commitmentId)?.title}</h3><p>{capitalize(details(o.commitmentId)?.scope ?? '')} · {own.find(p => p.id === o.planId)?.title}</p></div><Badge tone={o.status}>{capitalize(o.status)}</Badge><Button variant="secondary" onClick={() => open(o.id)}>Update</Button></div>)}</section>)}</div> : <Card><Empty title="No occurrences match these filters" description="Choose another status or scope to see your planned work." action={<Button onClick={() => { setStatus('all'); setScope('all'); }}>Clear filters</Button>}/></Card>}
 {edit && <OccurrenceEditor id={edit} onClose={() => setParams({})}/>}</>;
}
export function OccurrenceEditor({ id, onClose }: {
    id: string;
    onClose: () => void;
}) {
    const user = useUser()!, dispatch = useAppDispatch(), occurrence = useAppSelector(s => s.planning.occurrences[id]), plans = useAppSelector(s => s.planning.plans), all = useAppSelector(s => s.planning.occurrences), [status, setStatus] = useState<OccurrenceStatus>(occurrence?.status ?? 'scheduled'), [note, setNote] = useState(occurrence?.note ?? ''), [date, setDate] = useState(occurrence?.date ?? ''), [errors, setErrors] = useState<string[]>([]);
    const plan = occurrence && plans[occurrence.planId], activity = plan?.items.find(c => c.id === occurrence?.commitmentId)?.activity;
    const allowed = plan && plan.ownerId === user.id && plan.orgId === user.orgId;
    if (!allowed || !occurrence)
        return <Modal title="This occurrence is not available" onClose={onClose}><Notice tone="warning">Only the current demo identity’s own records can be opened through this view.</Notice></Modal>;
    const locked = plan.status === 'closed';
    return <Modal title={activity?.title ?? 'Activity occurrence'} onClose={onClose}><div className="row"><Badge tone={activity?.theme}>{capitalize(activity?.scope ?? '')}</Badge><Badge>{date}</Badge></div><Notice>This update applies to this occurrence only. {locked ? 'This month is closed. Create a correction from the plan to make changes.' : 'Edit future recurrence dates from the monthly plan.'}</Notice><ErrorSummary errors={errors}/><div className="stack"><Field label="Current status"><div className="status-buttons">{statuses.map(s => <button key={s} disabled={locked} className={s === status ? 'active' : ''} aria-pressed={s === status} onClick={() => setStatus(s)}>{capitalize(s)}</button>)}</div></Field><Field label="Occurrence date" id="occurrence-date" hint="Completed or cancelled dates are preserved."><input id="occurrence-date" type="date" min={`${plan.month}-01`} max={monthEnd(plan.month)} value={date} onChange={e => setDate(e.target.value)} disabled={locked || ['completed', 'cancelled'].includes(occurrence.status)}/></Field><Field label="Private implementation note (optional)" id="occurrence-note" hint="Not included in any organization or Taleed summary."><textarea id="occurrence-note" value={note} maxLength={5000} disabled={locked} onChange={e => setNote(e.target.value)} placeholder="What happened? What might you adjust? Use fictional details only."/></Field></div><div className="form-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={locked} onClick={() => {
            const e: string[] = [];
            if (!validDate(date) || !date.startsWith(plan.month))
                e.push('Choose a valid date inside this plan’s month.');
            if (Object.values(all).some(o => o.id !== id && o.planId === plan.id && o.commitmentId === occurrence.commitmentId && o.date === date))
                e.push('This commitment already has an occurrence on that date.');
            if (e.length) {
                setErrors(e);
                return;
            }
            dispatch(actions.planning.updateOccurrence({ occurrence: { ...occurrence, date, status, note }, ownerId: user.id, orgId: user.orgId }));
            dispatch(actions.ui.toast('Occurrence updated. Check the local save indicator.'));
            onClose();
        }}>Save update<Check size={16}/></Button></div></Modal>;
}

