import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function open(page:Page,path='/home'){await page.goto('/#'+path);await expect(page.getByLabel('Demo persona')).toBeVisible();}
test('seed dashboard loads and persists preferences across refresh',async({page})=>{await open(page);await expect(page.getByRole('heading',{name:'Small steps. Stronger teams.'})).toBeVisible();await page.getByLabel('Workspace month').fill('2026-10');await expect(page.getByText('Saved on this browser',{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('Workspace month')).toHaveValue('2026-10');});
test('Pick-3 blocks missing selections',async({page})=>{await open(page,'/plan/new');await page.getByLabel('Planning month',{exact:true}).fill('2026-10');await page.getByRole('button',{name:/Continue/}).click();await page.getByRole('button',{name:/Continue/}).click();await expect(page.getByRole('alert').filter({hasText:'Choose one available activity per scope'})).toBeVisible();});
test('different leader cannot open a private plan',async({page})=>{await open(page);await page.getByLabel('Demo persona').selectOption('leader-b');await page.goto('/#/plan/plan-current');await expect(page.getByRole('heading',{name:/not available/i})).toBeVisible();await expect(page.getByRole('heading',{name:'Make learning part of everyday work'})).toHaveCount(0);});
test('analyst cannot drill into private wellbeing',async({page})=>{await open(page);await page.getByLabel('Demo persona').selectOption('analyst');await page.goto('/#/wellbeing');await expect(page.getByRole('heading',{name:'This view is not part of your demo role'})).toBeVisible();});
test('local save failure is not reported as saved and retry recovers',async({page})=>{await open(page,'/settings');await page.getByLabel('Simulate a local save failure',{exact:true}).check();await page.getByLabel('Calendar week starts on').selectOption('1');await expect(page.getByText('Changes not saved',{exact:true})).toBeVisible();await page.getByLabel('Simulate a local save failure',{exact:true}).uncheck();await page.getByRole('button',{name:'Retry saving',exact:true}).click();await expect(page.getByText('Saved on this browser',{exact:true})).toBeVisible();});
test('source administration is role-guarded',async({page})=>{await open(page,'/admin');await expect(page.getByRole('heading',{name:'This view is not part of your demo role'})).toBeVisible();await page.getByLabel('Demo persona').selectOption('admin');await expect(page.getByRole('heading',{name:'Useful guidance. Clear provenance.'})).toBeVisible();});
test('dashboard has no serious or critical automatically detected accessibility issues',async({page})=>{await open(page);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.filter(v=>v.impact==='critical'||v.impact==='serious')).toEqual([]);});
test('representative pages do not overflow the viewport',async({page})=>{for(const path of ['/home','/library','/plan/plan-current','/conversations','/wellbeing','/settings']){await open(page,path);const size=await page.evaluate(()=>({viewport:innerWidth,content:document.documentElement.scrollWidth}));expect(size.content,`${path} horizontal page overflow`).toBeLessThanOrEqual(size.viewport+2);}});
