import { useState } from 'react';
import { DatabaseBackup, Download, RotateCcw, ShieldCheck, Upload } from 'lucide-react';
import { useAppDispatch, useAppSelector } from '../../app/hooks';
import { selectUser, selectSettingsState } from '../../app/selectors';
import { actions } from '../../app/slices';
import { persistedData, reloadStored, replaceData, repository } from '../../app/store';
import { makeSeed } from '../../data/seed';
import type { Envelope } from '../../domain/types';
import { migrateAndParse, MAX_BYTES } from '../../services/repository';
import { downloadFile } from '../../services/download';
import { ActionLink, Badge, Button, Card, Confirm, Field, Modal, Notice, PageHeader } from '../../components/UI';
export default function Settings() {
    const state = useAppSelector(selectSettingsState), user = useAppSelector(selectUser)!, dispatch = useAppDispatch();
    const [error, setError] = useState(''), [preview, setPreview] = useState<Envelope | null>(null), [confirm, setConfirm] = useState<'reset' | 'private-delete' | 'backup' | 'raw' | 'personal' | null>(null), [orgName, setOrgName] = useState(state.organization.organizations[user.orgId]?.name ?? ''), [city, setCity] = useState(state.organization.organizations[user.orgId]?.city ?? '');
    const isAdmin = user.role === 'admin', isPersonal = ['leader', 'champion'].includes(user.role);
    const run = (fn: () => void) => {
        try {
            fn();
            setError('');
        }
        catch (e) {
            setError(e instanceof Error ? e.message : 'The operation could not be completed. Existing stored data has not been intentionally removed.');
        }
    };
    const exportAll = () => downloadFile('taleed-DEVELOPER-ALL-FICTIONAL-DATA.json', JSON.stringify({ schemaVersion: 2, revision: repository.revision, clientId: repository.clientId, savedAt: new Date().toISOString(), data: persistedData(state) }, null, 2));
    const exportMine = () => downloadFile('taleed-my-personal-demo-records.json', JSON.stringify({ classification: 'PRIVATE DEMONSTRATION DATA', owner: user.name, exportedAt: new Date().toISOString(), plans: Object.values(state.planning.plans).filter(x => x.ownerId === user.id), snapshots: Object.values(state.planning.snapshots).filter(x => x.ownerId === user.id), conversations: Object.values(state.privateData.conversations).filter(x => x.ownerId === user.id), wellbeing: Object.values(state.privateData.wellbeing).filter(x => x.ownerId === user.id) }, null, 2));
    async function loadImport(file?: File) {
        if (!file)
            return;
        try {
            if (file.size > MAX_BYTES)
                throw new Error('This backup is larger than the 2 MB prototype limit.');
            setPreview(migrateAndParse(await file.text()));
            setError('');
        }
        catch (e) {
            setError(e instanceof Error ? e.message : 'This backup could not be read.');
        }
    }
    return <><PageHeader eyebrow="Account & demonstration controls" title="Your workspace, your preferences" description="Manage this browser’s demo data. Nothing on this page configures a real account, cloud service or security policy."/>{error && <Notice tone="error">{error}</Notice>}<div className="two-col"><Card><h2>Experience preferences</h2><Field label="Calendar week starts on" id="week-start"><select id="week-start" value={state.preferences.weekStart} onChange={e => dispatch(actions.preferences.set({ weekStart: Number(e.target.value) as 0 | 1 | 6 }))}><option value={0}>Sunday</option><option value={1}>Monday</option><option value={6}>Saturday</option></select></Field><label className="check-row"><input type="checkbox" checked={state.preferences.rtl} onChange={e => dispatch(actions.preferences.set({ rtl: e.target.checked }))}/>Preview right-to-left layout</label><p className="field-hint">Layout direction changes; English content remains English. This is not an Arabic translation.</p><label className="check-row"><input type="checkbox" checked={state.preferences.reminders} onChange={e => dispatch(actions.preferences.set({ reminders: e.target.checked }))}/>Remember my preference for neutral reminders</label><p className="field-hint">Preference only. No email, push notification, background schedule or calendar synchronization is sent by this demo.</p></Card><Card><h2>Data and saving</h2><dl className="details-list"><div><dt>Storage</dt><dd>Local to this browser and origin</dd></div><div><dt>Schema</dt><dd>Version 2 · migration from compatible v1</dd></div><div><dt>Known revision</dt><dd>{repository.revision}</dd></div><div><dt>Last successful save</dt><dd>{state.ui.savedAt ? new Date(state.ui.savedAt).toLocaleString('en-GB') : 'Seed data only—no changes saved yet'}</dd></div><div><dt>Current status</dt><dd><Badge tone={state.ui.saveStatus === 'saved' ? 'success' : 'warning'}>{state.ui.saveStatus}</Badge></dd></div></dl><Notice>Browser storage is readable by someone with access to this device. Do not enter real employee details, health information, passwords or production records.</Notice></Card></div>{user.role === 'champion' && <Card><h2>Organization settings</h2><p className="muted">Settings for your current fictional company; historical shared snapshots keep their original organization name.</p><div className="two-col"><Field label="Company name" id="organization-name"><input id="organization-name" maxLength={120} value={orgName} onChange={e => setOrgName(e.target.value)}/></Field><Field label="City" id="organization-city"><input id="organization-city" maxLength={100} value={city} onChange={e => setCity(e.target.value)}/></Field></div><Button onClick={() => run(() => {
                if (orgName.trim().length < 2 || !city.trim())
                    throw new Error('Add a company name and city.');
                if (Object.values(state.organization.organizations).some(o => o.id !== user.orgId && o.name.toLowerCase() === orgName.trim().toLowerCase()))
                    throw new Error('This name is already in use in the demo.');
                dispatch(actions.organization.saveOrganization({ ...state.organization.organizations[user.orgId]!, name: orgName.trim(), city: city.trim() }));
                dispatch(actions.ui.toast('Company details updated in this demo.'));
            })}>Save company details</Button></Card>}{isPersonal && <Card><h2>Personal records</h2><p>Export only your own records. Deleting conversations and well-being entries does not delete monthly plans, plan reflections, shared summaries or previously downloaded files.</p><div className="row"><Button variant="secondary" onClick={() => setConfirm('personal')}><Download size={16}/>Export my personal records</Button><Button variant="danger" onClick={() => setConfirm('private-delete')}>Delete my conversations & well-being</Button></div><p className="field-hint">No production retention duration or account-deletion policy is implied. Those require approval before real data is collected.</p></Card>}<Card><h2>Failure and recovery demonstration</h2><p>These controls let the team demonstrate honest saving and recovery states using fictional data.</p><label className="check-row"><input type="checkbox" checked={state.ui.failSaves} onChange={e => dispatch(actions.ui.failSaves(e.target.checked))}/>Simulate a local save failure</label><p className="field-hint">Make a change after enabling. “Saved” will not be shown. Disable the simulation, then retry.</p><div className="row"><Button variant="secondary" onClick={() => dispatch(actions.ui.retry())}>Retry saving</Button><Button variant="secondary" onClick={() => {
            if (window.confirm('Replace unsaved in-memory changes with the last successful stored version? Export a backup first when needed.'))
                run(reloadStored);
        }}>Reload stored data</Button><Button variant="ghost" onClick={() => dispatch(actions.ui.issue({ status: 'conflict', message: 'Simulated stale-tab conflict. This is a demo state, not evidence of a real simultaneous edit. Reload stored data after preserving any changes.' }))}>Preview conflict state</Button></div></Card>{isAdmin ? <Card className="developer-panel"><p className="eyebrow">Developer recovery console · Not a production feature</p><h2><DatabaseBackup size={22}/> All-persona demo backup</h2><Notice tone="warning">This developer-only view exposes a full backup containing every fictional persona’s records. It deliberately demonstrates that local storage cannot provide real privacy or tenant security. It must not ship as a participant feature in production.</Notice><div className="row"><Button variant="secondary" onClick={() => setConfirm('backup')}><Download size={16}/>Export in-memory backup</Button><Button variant="secondary" onClick={() => setConfirm('raw')}>Export original stored bytes</Button><label className="button secondary"><Upload size={16}/>Import demo backup<input className="visually-hidden" type="file" accept="application/json,.json" onChange={e => { void loadImport(e.target.files?.[0]); e.target.value = ''; }}/></label><Button variant="danger" onClick={() => setConfirm('reset')}><RotateCcw size={16}/>Reset demonstration</Button></div><p className="field-hint">Import is validated before replacement. Unsupported or corrupted files do not trigger automatic deletion. Reset intentionally replaces all demo records with the September 2026 scenario.</p></Card> : <Notice>For full backup/import/reset demonstrations, switch to the Content Administrator persona and open this page. This is a development console, not real administrator security.</Notice>}{confirm && <Confirm title={confirm === 'reset' ? 'Replace all demonstration data?' : confirm === 'private-delete' ? 'Delete your private exercises?' : 'Export demonstration information?'} description={confirm === 'reset' ? 'All current local demo records will be replaced with the original fictional scenario. Download a backup first. This cannot undo previously downloaded files.' : confirm === 'private-delete' ? 'This permanently removes your conversations and well-being entries from the current demo state. Other personas, monthly plan notes, snapshots and exported copies are not deleted.' : confirm === 'personal' ? 'Your own private notes and personal scores may be included. Keep the downloaded file confidential.' : 'This developer backup can include ALL fictional personas and their private data. Use only for approved local prototype testing; never real client or employee data.'} danger={confirm === 'reset' || confirm === 'private-delete'} onClose={() => setConfirm(null)} onConfirm={() => run(() => {
                if (confirm === 'reset') {
                    replaceData(makeSeed());
                    location.hash = '/home';
                }
                else if (confirm === 'private-delete') {
                    dispatch(actions.privateData.deleteMine(user.id));
                    dispatch(actions.ui.toast('Your conversation and well-being entries were removed from the demo.'));
                }
                else if (confirm === 'personal')
                    exportMine();
                else if (confirm === 'backup')
                    exportAll();
                else {
                    const raw = repository.raw();
                    if (raw === null)
                        throw new Error('No stored data exists yet. Export the in-memory backup instead.');
                    downloadFile('taleed-original-stored-data.txt', raw, 'text/plain');
                }
            })}/>} {preview && <Modal title="Replace the current demo with this backup?" onClose={() => setPreview(null)}><p>The file passed schema and relationship checks. Replacing the demo affects all fictional personas, not just your current view.</p><dl className="details-list"><div><dt>File saved</dt><dd>{preview.savedAt}</dd></div><div><dt>Companies</dt><dd>{Object.keys(preview.data.organization.organizations).length}</dd></div><div><dt>Plans</dt><dd>{Object.keys(preview.data.planning.plans).length}</dd></div><div><dt>Source schema</dt><dd>Compatible v2 (migrated if necessary)</dd></div></dl><Notice tone="warning">Export the current in-memory or stored backup first. Imported content must be fictional and authorized.</Notice><div className="form-actions"><Button variant="secondary" onClick={() => setPreview(null)}>Cancel</Button><Button onClick={() => run(() => { replaceData(preview.data); setPreview(null); location.hash = '/home'; })}>Replace with validated backup</Button></div></Modal>}</>;
}
export function About() { return <><PageHeader eyebrow="Help & scope" title="Turn guidance into everyday practice" description="A guided Talent & Team Development workspace, built for prototype review—not real employee records."/><Card><h2>Choose → Plan → Do → Reflect → Repeat</h2><p>Choose one focus theme. Select one individual, one culture and one team activity. Schedule the work, record what actually happens and close the month honestly. Conversations and well-being are optional personal exercises.</p><div className="three-col"><div><h3>Team Leader</h3><p>Own plans, calendar, conversations, personal reflections and reports.</p></div><div><h3>SME Champion</h3><p>Own leader journey, invitations, organization settings and explicitly shared aggregate summaries.</p></div><div><h3>Taleed team</h3><p>Only shared company summaries for the assigned demonstration cohort. No personal drill-through.</p></div></div></Card><Card><h2>What this demo does not do</h2><p>It does not authenticate users, verify email ownership, send invitations, enforce server-side permissions, store real PDFs, synchronize calendars, send reminders, provide medical advice or measure employee performance. It is not an HR information system, a procurement assessment or a maturity-scoring product.</p><Notice><ShieldCheck size={18}/> Personal privacy is a proposed production boundary, simulated in the interface. A local browser application cannot make records secure from someone who controls the browser.</Notice></Card><Card><h2>How to present it</h2><p>Begin as Amina Hassan. Explore the September plan, update an occurrence, or create a new plan for October. Switch to Noor Saleh, select August and share the seeded closed-month summary. Then switch to Mariam Ahmed to see exactly the same safe snapshot. Open Settings as the administrator to test recovery.</p><div className="row"><ActionLink to="/home">Open workspace</ActionLink><ActionLink secondary to="/settings">Demo controls</ActionLink></div></Card><Card><h2>Design and source status</h2><p>The color direction is provisional and inspired by the supplied Taleed prototype reference. The official product kit, logo and licensed typography are not included. The activity collection and conversation copy are explicitly illustrative until the client’s approved source JSON and brand assets are supplied.</p><p className="muted">Prepared for Fadi Zahhar · 15 September 2026 · Internal review prototype</p></Card></>; }

