/** Runs the actual pure domain modules without React, Redux or a DOM. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';import {webcrypto} from 'node:crypto';
import {loadTypeScript} from './typescript-runtime.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),ts=loadTypeScript(),cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const mod={exports:{}};cache.set(file,mod);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;const require=ref=>{if(!ref.startsWith('.'))throw new Error(`External dependency not allowed in pure tests: ${ref}`);return load(path.resolve(path.dirname(file),ref+'.ts'));};const wrapper=vm.runInThisContext(`(function(require,module,exports){${code}\n})`,{filename:file});wrapper(require,mod,mod.exports);return mod.exports;}
globalThis.crypto??=webcrypto;
const L=load(path.join(root,'src/domain/logic.ts')),T=load(path.join(root,'src/domain/types.ts')),{makeSeed}=load(path.join(root,'src/data/seed.ts'));
const results=[];function test(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',message:e.message});}}
const seed=makeSeed(),past=seed.planning.snapshots['snapshot-seed'];
const sample={id:'test',ownerId:'leader-a',month:'2026-09',scores:L.emptyScores(),focus:'',actions:['','',''],status:'draft',revision:1,updatedAt:'2026-09-15T12:00:00Z'};
const schedule={cadence:'weekly',start:'2026-09-01',end:'2026-09-30',weekdays:[2]};
test('Catalogue contains 72 explicitly illustrative/reference-equivalent cards',()=>assert.equal(Object.keys(seed.catalogue.activities).length,72));
test('Each theme/scope contains six cards',()=>{for(const theme of T.themes)for(const scope of T.scopes)assert.equal(Object.values(seed.catalogue.activities).filter(a=>a.theme===theme&&a.scope===scope).length,6);});
test('Seven source metadata records exist',()=>assert.equal(Object.keys(seed.catalogue.resources).length,7));
test('Leap day 2028 is valid',()=>assert.equal(L.validDate('2028-02-29'),true));
test('Non-leap day 2026 is rejected',()=>assert.equal(L.validDate('2026-02-29'),false));
test('Impossible April 31 is rejected',()=>assert.equal(L.validDate('2026-04-31'),false));
test('Month range and format are validated',()=>{for(const m of ['2026-00','2026-13','1999-12','2101-01','2026-9'])assert.equal(L.validMonth(m),false);});
test('February leap-year end is correct',()=>assert.equal(L.monthEnd('2028-02'),'2028-02-29'));
test('Calendar supports four displayed weeks',()=>assert.equal(L.calendarDays('2026-02',0).length,28));
test('Calendar supports five displayed weeks',()=>assert.equal(L.calendarDays('2026-09',0).length,35));
test('Calendar supports six displayed weeks',()=>assert.equal(L.calendarDays('2026-05',0).length,42));
test('Monday week start is respected',()=>assert.equal(L.dateUTC(L.calendarDays('2026-09',1)[0].date).getUTCDay(),1));
test('Year rollover works',()=>assert.equal(L.offsetMonth('2026-12',1),'2027-01'));
test('Weekly occurrence dates are deterministic',()=>assert.deepEqual(L.expandSchedule(schedule),['2026-09-01','2026-09-08','2026-09-15','2026-09-22','2026-09-29']));
test('Daily recurrence covers all days, including weekends',()=>assert.equal(L.expandSchedule({...schedule,cadence:'daily'}).length,30));
test('One-off creates exactly one occurrence',()=>assert.equal(L.expandSchedule({...schedule,cadence:'once'}).length,1));
test('Weekly schedule requires chosen weekdays',()=>assert.ok(L.validateSchedule({...schedule,weekdays:[]},'2026-09','develop').length));
test('Schedules cannot cross the selected month',()=>assert.ok(L.validateSchedule({...schedule,end:'2026-10-01'},'2026-09','develop').length));
test('One-off is rejected outside Develop',()=>assert.ok(L.validateSchedule({...schedule,cadence:'once'},'2026-09','care').length));
test('No-matching-weekday schedule is rejected',()=>assert.ok(L.validateSchedule({...schedule,start:'2026-09-01',end:'2026-09-01',weekdays:[3]},'2026-09','develop').length));
test('Generated occurrence identities are stable on repeated expansion',()=>{const p=seed.planning.plans['plan-current'];assert.deepEqual(L.generateOccurrences(p.id,p.items),L.generateOccurrences(p.id,p.items));});
const draft={id:'draft:test',ownerId:'leader-a',orgId:'cedar',month:'2026-09',title:'Test',theme:'develop',selected:{individual:'develop-individual-1',culture:'develop-culture-1',team:'develop-team-1'},schedules:{},step:1};
test('One activity per scope satisfies Pick-3',()=>assert.deepEqual(L.starterErrors(draft,seed.catalogue.activities),[]));
test('Three choices from one scope are rejected',()=>assert.ok(L.starterErrors({...draft,selected:{individual:'develop-individual-1',culture:'develop-individual-2',team:'develop-individual-3'}},seed.catalogue.activities).length));
test('Mixed theme selections are rejected',()=>assert.ok(L.starterErrors({...draft,selected:{...draft.selected,team:'care-team-1'}},seed.catalogue.activities).length));
test('Retired content is rejected in a new plan',()=>{const catalog=structuredClone(seed.catalogue.activities);catalog['develop-team-1'].status='retired';assert.ok(L.starterErrors(draft,catalog).length);});
test('Cancelled occurrence excluded: two of four = 50%',()=>{const m=L.planMetrics(past.plan,past.occurrences);assert.equal(m.scheduled,5);assert.equal(m.cancelled,1);assert.equal(m.eligible,4);assert.equal(m.completed,2);assert.equal(m.rate,50);});
test('Delivered scopes are two, not three selected cards',()=>assert.deepEqual(L.planMetrics(past.plan,past.occurrences).coverage,['individual','team']));
test('No scheduled activity has a null rate, not 0 or 100',()=>assert.equal(L.planMetrics(past.plan,[]).rate,null));
test('Zero eligible denominator is also null',()=>assert.equal(L.planMetrics(past.plan,past.occurrences.map(o=>({...o,status:'cancelled'}))).rate,null));
test('Higher closed revision replaces—not adds to—summary',()=>{const newer={...structuredClone(past),id:'snap-v2',revision:2};assert.equal(L.currentSnapshots([past,newer]).length,1);assert.equal(L.currentSnapshots([past,newer])[0].revision,2);});
test('Summary excludes private notes, custom titles and identity',()=>{const payload=L.safeSummary('cedar','Cedar Works',past.month,[past],1,'2026-09-15T12:00:00Z'),text=JSON.stringify(payload);for(const forbidden of ['ownerId','Synthetic private note','We made a useful start','Amina','wellbeing','conversation','Find mentors'])assert.equal(text.includes(forbidden),false);assert.equal(payload.completed,2);assert.equal(payload.fullyCoveredDevelopmentPlans,0);});
test('Summary filters other company and month',()=>{const s=L.safeSummary('dune','Dune Studio',past.month,[past],1,'now');assert.equal(s.closedPlans,0);assert.equal(L.safeSummary('cedar','Cedar Works','2026-09',[past],1,'now').closedPlans,0);});
test('Blank well-being dimensions have no total',()=>assert.equal(L.wheelTotal(sample.scores),null));
test('Eight ratings do not generate a total',()=>{const scores=Object.fromEntries(T.dimensions.map((d,i)=>[d,i===8?null:6]));assert.equal(L.wheelTotal(scores),null);});
test('Source numeric example totals 54',()=>{const scores=Object.fromEntries(T.dimensions.map((d,i)=>[d,[8,7,8,3,6,3,6,8,5][i]]));assert.equal(L.wheelTotal(scores),54);});
test('Min/max numeric totals are 9 and 90',()=>{for(const v of [1,10])assert.equal(L.wheelTotal(Object.fromEntries(T.dimensions.map(d=>[d,v]))),v*9);});
test('Fractional, zero and out-of-range scores are rejected',()=>{for(const v of [0,11,2.5,NaN,true,'6']){const scores=Object.fromEntries(T.dimensions.map(d=>[d,6]));scores.Physical=v;assert.equal(L.wheelTotal(scores),null);}});
test('Complete reflection requires explicit focus and three actions',()=>{const w={...sample,scores:Object.fromEntries(T.dimensions.map(d=>[d,6]))};assert.equal(L.wheelErrors(w).length,2);assert.deepEqual(L.wheelErrors({...w,focus:'Digital',actions:['One','Two','Three']}),[]);});
test('Published-content edits cannot mutate a plan copy',()=>{const s=makeSeed();s.catalogue.activities['develop-individual-1'].title='A changed title';assert.notEqual(s.planning.plans['plan-current'].items[0].activity.title,'A changed title');});
test('CSV neutralizes formula-leading characters and escapes quotes',()=>{assert.equal(L.csvCell('=1+1'),'"\'=1+1"');assert.equal(L.csvCell('a"b'),'"a""b"');});
test('Calendar export excludes cancelled/private notes',()=>{const text=L.calendarFile(past.plan,past.occurrences);assert.equal((text.match(/BEGIN:VEVENT/g)||[]).length,4);assert.equal(text.includes('Synthetic private note'),false);assert.ok(text.includes('DTSTART;VALUE=DATE:20260805'));});
const report={checkedAt:new Date().toISOString(),node:process.versions.node,typescript:ts.version,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,scope:'Executed pure domain functions and synthetic seed only. React, Redux, Zod, browser interactions and dependency integration are NOT covered by this run.',results};
fs.mkdirSync(path.join(root,'docs'),{recursive:true});fs.writeFileSync(path.join(root,'docs/domain-test-results.json'),JSON.stringify(report,null,2)+'\n');for(const r of results)console.log(`${r.status} ${r.name}${r.message?' — '+r.message:''}`);console.log(`\n${report.passed} passed; ${report.failed} failed`);if(report.failed)process.exitCode=1;
