import { describe, expect, it } from 'vitest';
import { makeSeed } from '../src/data/seed';
import { actions, organizationSlice, planningSlice, privateSlice } from '../src/app/slices';
import { safeSummary } from '../src/domain/logic';
describe('Workflow reducers',()=>{
 it('does not update an occurrence for another owner',()=>{const seed=makeSeed(),old=seed.planning.occurrences['plan-current:commit-0:2026-09-03'];const next=planningSlice.reducer(seed.planning,actions.planning.updateOccurrence({occurrence:{...old,status:'cancelled'},ownerId:'leader-b',orgId:'cedar'}));expect(next).toEqual(seed.planning);});
 it('does not update closed occurrences',()=>{const seed=makeSeed(),old=seed.planning.occurrences['past-o1'];const next=planningSlice.reducer(seed.planning,actions.planning.updateOccurrence({occurrence:{...old,status:'scheduled'},ownerId:'leader-a',orgId:'cedar'}));expect(next).toEqual(seed.planning);});
 it('reopens a closed plan with a new revision and preserves the snapshot',()=>{const seed=makeSeed(),next=planningSlice.reducer(seed.planning,actions.planning.reopen({planId:'plan-closed',ownerId:'leader-a'}));expect(next.plans['plan-closed'].revision).toBe(2);expect(next.snapshots['snapshot-seed']).toEqual(seed.planning.snapshots['snapshot-seed']);});
 it('keeps a single effective shared organization/month summary',()=>{const seed=makeSeed(),payload=safeSummary('cedar','Cedar Works','2026-08',Object.values(seed.planning.snapshots),1,'2026-09-15');const first=organizationSlice.reducer(seed.organization,actions.organization.share({id:'share-1',status:'shared',payload}));const second=organizationSlice.reducer(first,actions.organization.share({id:'share-2',status:'shared',payload:{...payload,version:2}}));expect(second.summaries['share-1'].status).toBe('superseded');expect(second.summaries['share-2'].status).toBe('shared');});
 it('rejects revoked or wrong-account invitation acceptance',()=>{const seed=makeSeed(),i={id:'invite',orgId:'cedar',name:'Test',email:'test@example.test',status:'revoked' as const,expiresAt:'2026-09-22'};const state={...seed.organization,invitations:{invite:i}};const next=organizationSlice.reducer(state,actions.organization.acceptInvitation({id:'invite',user:{id:'new-user',name:'Test',email:i.email,orgId:'cedar',role:'leader'},now:'2026-09-15'}));expect(next.users['new-user']).toBeUndefined();});
 it('private delete does not remove another person’s conversation',()=>{const seed=makeSeed();seed.privateData.conversations.other={id:'other',ownerId:'leader-b',month:'2026-09',alias:'Fictional',date:'',answers:['','',''],goal:'',nextStep:'',followup:'',status:'draft',updatedAt:'2026-09-15'};const next=privateSlice.reducer(seed.privateData,actions.privateData.deleteMine('leader-a'));expect(next.conversations.other).toBeDefined();});
});
