import { describe, expect, it } from 'vitest';
import { makeSeed } from '../src/data/seed';
import { LocalRepository, migrateAndParse, STORAGE_KEY, StorageConflict, type StoragePort } from '../src/services/repository';
class MemoryStorage implements StoragePort{entries=new Map<string,string>();fail=false;getItem(key:string){return this.entries.get(key)??null;}setItem(key:string,value:string){if(this.fail)throw new DOMException('Quota exceeded','QuotaExceededError');this.entries.set(key,value);}removeItem(key:string){this.entries.delete(key);}}
describe('Versioned local repository',()=>{
 it('round-trips seed data through strict schema validation',()=>{const storage=new MemoryStorage(),repo=new LocalRepository(storage,'a');repo.save(makeSeed());expect(repo.read()?.data).toEqual(makeSeed());expect(repo.revision).toBe(1);});
 it('never increments revision after failed setItem',()=>{const storage=new MemoryStorage(),repo=new LocalRepository(storage,'a');repo.save(makeSeed());const before=storage.getItem(STORAGE_KEY);storage.fail=true;expect(()=>repo.save(makeSeed())).toThrow();expect(repo.revision).toBe(1);expect(storage.getItem(STORAGE_KEY)).toBe(before);});
 it('detects stale revision before overwriting another tab',()=>{const storage=new MemoryStorage(),a=new LocalRepository(storage,'a'),b=new LocalRepository(storage,'b');a.save(makeSeed());b.read();a.save(makeSeed());expect(()=>b.save(makeSeed())).toThrow(StorageConflict);});
 it('retains corrupt data rather than replacing it on read',()=>{const storage=new MemoryStorage();storage.setItem(STORAGE_KEY,'{not json');const repo=new LocalRepository(storage,'a');expect(()=>repo.read()).toThrow();expect(repo.raw()).toBe('{not json');});
 it('failed replacement leaves the previous bytes intact',()=>{const storage=new MemoryStorage(),repo=new LocalRepository(storage,'a');repo.save(makeSeed());const before=repo.raw();storage.fail=true;expect(()=>repo.replace(makeSeed('2026-10'))).toThrow();expect(repo.raw()).toBe(before);});
 it('migrates only the explicitly supported v1 shape',()=>{const storage=new MemoryStorage(),repo=new LocalRepository(storage,'a');const old=JSON.parse(JSON.stringify(repo.save(makeSeed())));old.schemaVersion=1;delete old.data.preferences.weekStart;expect(migrateAndParse(JSON.stringify(old)).data.preferences.weekStart).toBe(0);expect(()=>migrateAndParse(JSON.stringify({...old,schemaVersion:999}))).toThrow();});
 it('rejects malformed entity references and unknown fields',()=>{const storage=new MemoryStorage(),repo=new LocalRepository(storage,'a');const file=repo.save(makeSeed());file.data.planning.occurrences['past-o1'].planId='missing';expect(()=>migrateAndParse(JSON.stringify(file))).toThrow();});
 it('rejects unknown preference fields',()=>{const storage=new MemoryStorage(),repo=new LocalRepository(storage,'a');const file=repo.save(makeSeed());(file.data.preferences as unknown as Record<string,unknown>).surprise=true;expect(()=>migrateAndParse(JSON.stringify(file))).toThrow();});
});
