import { ArrowRight, CalendarDays, Check, Heart, Leaf, Lightbulb, MessageCircle, Plus, Sparkles, Target, Users } from 'lucide-react';
import { Link, Navigate } from 'react-router-dom';
import { useAppSelector, useUser } from '../../app/hooks';
import { selectOwnPlans } from '../../app/selectors';
import { capitalize, dayLabel, monthLabel, planMetrics } from '../../domain/logic';
import { themes } from '../../domain/types';
import { themeDescriptions } from '../../data/catalogue';
import { ActionLink, Badge, Card, Empty, PageHeader, Progress, ScopeCoverage, Stat, TextLink } from '../../components/UI';
const icons = { care: Heart, develop: Leaf, enable: Lightbulb, recognition: Sparkles };
export function ThemeIcon({ theme }: {
    theme: typeof themes[number];
}) { const Icon = icons[theme]; return <div className={`icon-box ${theme}`}><Icon size={21}/></div>; }
export function HeroArt() { return <div className="hero-art" aria-hidden="true"><div className="orbit"/><div className="orbit"/><div className="orbit"/><div className="orbit"/><div className="leaf"/><div className="leaf second"/><div className="leaf third"/><div className="spark"/><div className="spark"/></div>; }
export default function Home() {
    const user = useUser()!, month = useAppSelector(s => s.preferences.month), plans = useAppSelector(selectOwnPlans), occurrences = useAppSelector(s => s.planning.occurrences), draft = useAppSelector(s => s.planning.drafts[`draft:${user.id}`]);
    if (user.role === 'taleed')
        return <Navigate to="/portfolio" replace/>;
    if (user.role === 'admin')
        return <Navigate to="/admin" replace/>;
    const plan = plans.find(p => p.month === month), metric = plan ? planMetrics(plan, Object.values(occurrences)) : null;
    const upcoming = plan ? Object.values(occurrences).filter(o => o.planId === plan.id && !['completed', 'cancelled'].includes(o.status)).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 3) : [];
    return <><PageHeader eyebrow="YOUR LEADERSHIP WORKSPACE" title={`Small steps. Stronger teams.`} description={`Welcome back, ${user.name.split(' ')[0]}. Make space for the people and practices that matter.`} action={<ActionLink to="/plan/new"><Plus size={16}/>{draft ? 'Resume draft' : 'Build a plan'}</ActionLink>}/>
 <div className="main-grid"><section className="hero-card"><div className="hero-copy"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Turn good intentions<br />into everyday practice.</h2><p>One individual. Your workplace culture. The whole team.<br />Choose three meaningful actions and make them happen.</p><ActionLink to={plan ? `/plan/${plan.id}` : '/plan/new'}>{plan ? 'Continue my monthly plan' : 'Choose my first three'}<ArrowRight size={16}/></ActionLink></div><HeroArt /></section><Card className="hero-side"><div><div className="icon-box"><MessageCircle size={21}/></div><Badge>PERSONAL DEVELOPMENT</Badge><h3 className="mt">A good conversation<br />can open new possibilities.</h3><p>Prepare a thoughtful check-in. Listen, explore and agree one helpful next step.</p></div><TextLink to="/conversations">Prepare a conversation</TextLink></Card></div>
 <div className="stats-grid"><Stat label="Your focus this month" value={plan ? capitalize(plan.theme) : 'Choose'} detail={monthLabel(month)} icon={<Target />}/><Stat label="Activities in your plan" value={plan?.items.length ?? 0} detail="A balanced starting point" icon={<CalendarDays />}/><Stat label="Completed occurrences" value={metric ? `${metric.completed}/${metric.eligible}` : '—'} detail={metric ? `${metric.cancelled} cancelled, excluded` : 'Your first action starts here'} icon={<Check />}/><Stat label="Scopes delivered" value={metric ? `${metric.coverage.length}/3` : '0/3'} detail="Individual · Culture · Team" icon={<Users />}/></div>
 <div className="main-grid"><Card><div className="card-header"><div><h2>Your next actions</h2><p>A little follow-through goes a long way.</p></div><TextLink to="/calendar">Open calendar</TextLink></div>{upcoming.length ? upcoming.map(o => { const activity = plan!.items.find(c => c.id === o.commitmentId)!.activity; return <div className="activity-line" key={o.id}><div className="date-tile"><strong>{o.date.slice(-2)}</strong><span>{new Date(`${o.date}T12:00:00Z`).toLocaleString('en', { month: 'short', timeZone: 'UTC' })}</span></div><div className="activity-body"><h3>{activity.title}</h3><p>{capitalize(activity.scope)} <span>·</span> <Badge tone={o.status}>{capitalize(o.status)}</Badge></p></div><Link className="button secondary small" to={`/calendar?occurrence=${encodeURIComponent(o.id)}`}>Update<ArrowRight size={13}/></Link></div>; }) : <Empty title={plan ? 'Your planned actions are up to date' : 'Begin with three activities'} description={plan ? 'Reflect on what helped, or revisit your plan.' : 'Choose one activity for each scope to start a balanced monthly practice.'} action={<ActionLink to={plan ? `/plan/${plan.id}` : '/plan/new'}>{plan ? 'Review plan' : 'Create a plan'}</ActionLink>}/>}</Card><Card><div className="card-header"><div><h2>{monthLabel(month).split(' ')[0]} at a glance</h2><p>Progress is practice, not a ranking.</p></div><Badge tone={plan?.status ?? 'draft'}>{plan?.status ?? 'Not started'}</Badge></div><div className="metric-pair"><div><strong>{metric?.rate === null || !metric ? '—' : `${metric.rate}%`}</strong><span>Self-reported follow-through</span></div></div>{metric && <Progress value={metric.rate ?? 0} label="Eligible occurrences completed"/>}<p className="small-text mt mb">Delivered scope coverage</p><ScopeCoverage coverage={metric?.coverage ?? []}/><div className="notification-card mt"><Leaf size={20} color="var(--blue)"/><div><h3>Consistency over perfection.</h3><p>You can close a month honestly, even when some activities are still incomplete.</p></div></div></Card></div>
 <div className="section-heading"><div><h2>Four ways to make a difference</h2><p>Choose a focus that feels useful for your team right now.</p></div><TextLink to="/library">Explore all activities</TextLink></div><div className="theme-grid">{themes.map(theme => <Link key={theme} to={`/library?theme=${theme}`} className="theme-card"><ThemeIcon theme={theme}/><h3>{capitalize(theme)}</h3><p>{themeDescriptions[theme].description}</p><small>18 sample activities <ArrowRight size={10}/></small></Link>)}</div><p className="screen-label">Demonstration content · Source approval and final Taleed brand alignment remain required.</p></>;
}

